server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/palikcuiho/config-server-git
          clone-on-start: true
          default-label: main
